### PR TITLE
Requirement view

### PR DESCRIPTION
**Pull request by istvank**
When calling a URL with a requirement, it is now opened in a separate requirement view. Previously, the category view was opened and often users had to scroll down to find the requested requirement.

### CODE REVIEW

**Comment by hexTileX** [comment]
Shall I review and merge?

**Comment by istvank** [comment]
sure, please. 😄

**Comment by hexTileX** [comment]
Do you want to make upload attachments in a second step / task?

**Comment by istvank** [comment]
Was uploading attachments connected to this issue?

**Pull request merged**
