### PR TITLE
Update main to new Vue.js based implementation (from develop)

### PR DESCRIPTION
**Pull request by fxjordan**
See #134 

The develop branch was prepared for merging using `git merge --allow-unrelated-histories -s ours main` because the old main branch was completely unrelated to develop.
Now, all Vue.js related commits from develop are shown as updates *after* the old Polymer based commits.

### CODE REVIEW

**Review by istvank — APPROVED** [review]
Looks good, since this is also the deployed version.

**Comment by fxjordan** [comment]
@istvank I think we need to add a LICENSE file before merging because the develop branch is currently missing one.

Should I just use the one from main without the Polymer section? (see https://github.com/rwth-acis/RequirementsBazaar-WebFrontend/blob/legacy-polymer-frontend/LICENSE.md)

**Comment by istvank** [comment]
Good point. Yes, please use the linked one, but you can remove the second sentence "However, ...." as well as the whole Polymer License, since we are no longer building on it.

Can you merge this pull request after I reviewed, or do I have to do it?

**Comment by fxjordan** [comment]
I can. I'll merge it later after adding the license.

**Pull request merged**
